### ISSUE TITLE
Navigating directly to a thread is broken

### ISSUE THREAD

**Issue by deklanw** [ryansolid/solid-hackernews-app#1]
https://ryansolid.github.io/solid-hackernews-app/stories/20371747

I'm assuming this is a routing issue with GH pages.

**Comment by ryansolid** [comment]
Yes you are correct. I used History PushState API but with GH pages I don't have a server always serving up the same page regardless of URL. I suppose I should switch to hashchange to allow for the same page to serve up. I just liked the look of PushState. Thanks for bringing this to my attention.

**Comment by ryansolid** [comment]
Changed to hashchange now. Refreshing/direct navigation will work.
