### ISSUE TITLE
Solid not running

### ISSUE THREAD

**Issue by jcuenod** [ryansolid/solid-hackernews-app#7]
I'm getting `Uncaught (in promise) TypeError: s is not a function` at https://ryansolid.github.io/solid-hackernews-app/

**Comment by ryansolid** [comment]
Oh weird. I see it. Thanks for reporting.

**Comment by ryansolid** [comment]
babel-loader cache was loading up an old version of the compiled code that wasn't compatible with the latest runtime. It worked locally in dev and I kept rebuilding it but getting the same issue. It should be resolved now. Thanks for bringing this to my attention.
